code/dte: add XML schemas of "factura electrónica"
cl-sii-extraoficial/archivos-oficiales pull request #13
Opened 2021-03-25 21:14 UTC by yaselc

Official XML schemas of DTE (Documento Tributario Electrónico)

Includes a README file by @glarrain

All the files have been preserved as they were; schemas are in their original text encoding (ISO-8859-1) and have not been modified in the slightest way.

Sources (2021-03-25):
http://www.sii.cl/factura_electronica/schema_dte.zip

Ref: #11 
Replaces #12

2021-03-29 17:50 UTC, jtrh requested changes

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/README.md
> +  - Version 2011-05-30(latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```suggestion
  - Version 2011-05-30 (latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/README.md
> +  - Version 2011-05-30(latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```suggestion
  - Version 2011-05-30 (latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/README.md
> +  - Version 2011-05-30(latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```suggestion
  - Version 2011-05-30 (latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/README.md
> +  - Version 2011-05-30(latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```suggestion
  - Version 2011-05-30 (latest): [2011-05-30-schema_dte/schema_dte](2011-05-30-schema_dte/schema_dte)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/README.md
> +- Fuente: [SII](http://www.sii.cl)
```suggestion
- Fuente: [SII](https://www.sii.cl)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/README.md
> +  / [Factura electrónica](http://www.sii.cl/servicios_online/1039-.html)
```suggestion
  / [Factura electrónica](https://www.sii.cl/servicios_online/1039-.html)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/README.md
> +  / [FORMATO XML DE DOCUMENTOS ELECTRÓNICOS](http://www.sii.cl/factura_electronica/formato_xml.htm)
```suggestion
  / [FORMATO XML DE DOCUMENTOS ELECTRÓNICOS](https://www.sii.cl/factura_electronica/formato_xml.htm)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/README.md
> +  "[Bajar schema XML de Documentos Tributarios Electrónicos](http://www.sii.cl/factura_electronica/schema_dte.zip) (Incluye Documentos de exportación)"
```suggestion
  "[Bajar schema XML de Documentos Tributarios Electrónicos](https://www.sii.cl/factura_electronica/schema_dte.zip) (Incluye Documentos de exportación)"
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/README.md
> +# SII "Documento Tributario Electrónico (DTE)"
Replace Windows line terminators (`CR LF`, `\r\n`) with Unix line terminators (`LF`, `\n`).

```
src/code/dte/README.md:  UTF-8 Unicode text, with CRLF line terminators
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/schema_dte/README.md
> +# SII "Documento Tributario Electrónico (DTE)" / XML schemas
Replace Windows line terminators (`CR LF`, `\r\n`) with Unix line terminators (`LF`, `\n`).

```
src/code/dte/2011-05-30-schema_dte/schema_dte/README.md: UTF-8 Unicode text, with CRLF line terminators
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/schema_dte/README.md
> +[SII](http://www.sii.cl)
```suggestion
[SII](https://www.sii.cl)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/schema_dte/README.md
> +/ [Factura electrónica](http://www.sii.cl/servicios_online/1039-.html)
```suggestion
/ [Factura electrónica](https://www.sii.cl/servicios_online/1039-.html)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/schema_dte/README.md
> +/ [FORMATO XML DE DOCUMENTOS ELECTRÓNICOS](http://www.sii.cl/factura_electronica/formato_xml.htm)
```suggestion
/ [FORMATO XML DE DOCUMENTOS ELECTRÓNICOS](https://www.sii.cl/factura_electronica/formato_xml.htm)
```

2021-03-29 17:50 UTC, jtrh commented on src/code/dte/2011-05-30-schema_dte/schema_dte/README.md
> +"[Bajar schema XML de Documentos Tributarios Electrónicos](http://www.sii.cl/factura_electronica/schema_dte.zip) (Incluye Documentos de exportación)"
```suggestion
"[Bajar schema XML de Documentos Tributarios Electrónicos](https://www.sii.cl/factura_electronica/schema_dte.zip) (Incluye Documentos de exportación)"
```

2021-03-29 22:14 UTC, glarrain approved these changes

2021-03-30 05:13 UTC, jtrh approved these changes

2021-03-30 11:54 UTC, merged