code/rtc: add XML schemas of "cesión"
cl-sii-extraoficial/archivos-oficiales pull request #14
Opened 2021-03-26 01:52 UTC by yaselc

Official XML schemas of AEC (Archivo Electrónico de Cesión)

Includes a README file by @glarrain

All the files have been preserved as they were; schemas are in their original text encoding (ISO-8859-1) and have not been modified in the slightest way.

Sources (2021-03-25):
https://www.sii.cl/factura_electronica/schema_cesion_201912.zip

Ref: #11

2021-03-26 01:52 UTC, yaselc commented
Don't merge before #12

2021-03-29 22:18 UTC, glarrain commented on src/code/rtc/2019-12-12-schema_cesion/schema_cesion/README.md
> +- RPETC: "Registro Público Electrónico de Transferencia de Crédito" aka RTC.|
```suggestion
- RPETC: "Registro Público Electrónico de Transferencia de Crédito" aka RTC.
```

2021-03-31 05:13 UTC, jtrh requested changes
- [x] MD5 checksums
- [x] SHA256 checksums
- [x] Hyperlink URLs

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/2019-12-12-schema_cesion/README.md
> +  "[Formato XML del Archivo Electrónico de Cesión](http://www.sii.cl/factura_electronica/schema_cesion.zip)"
https://www.sii.cl/factura_electronica/schema_cesion.zip exists, but is a different file, possibly an older version. It contains the same files as `schema_cesion_201912.zip`, but `DTE_v10.xsd` and `SiiTypes_v10.xsd` are different.

```
$ curl -s https://www.sii.cl/factura_electronica/schema_cesion.zip | md5sum
82d426fc3bd5f3a29e61a1d07ed4d6dd  -
$ curl -s https://www.sii.cl/factura_electronica/schema_cesion_201912.zip | md5sum
33639f61ef3aa0ec785557b1c8778cea  -
```

```suggestion
  "[Formato XML del Archivo Electrónico de Cesión](https://www.sii.cl/factura_electronica/schema_cesion_201912.zip)"
```

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/README.md
> +    - Identical to [xmldsignature_v10.xsd](../../../dte/2011-05-30-schema_dte/schema_dte/xmldsignature_v10.xsd) in the [DTE XML schema directory](../../../dte/2011-05-30-schema_dte/schema_dte).
```suggestion
    - Identical to [xmldsignature_v10.xsd](../dte/2011-05-30-schema_dte/schema_dte/xmldsignature_v10.xsd) in the [DTE XML schema directory](../dte/2011-05-30-schema_dte/schema_dte).
```

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/2019-12-12-schema_cesion/schema_cesion/README.md
> +"[Formato XML del Archivo Electrónico de Cesión](http://www.sii.cl/factura_electronica/schema_cesion.zip)"
https://www.sii.cl/factura_electronica/schema_cesion.zip exists, but is a different file, possibly an older version. It contains the same files as `schema_cesion_201912.zip`, but `DTE_v10.xsd` and `SiiTypes_v10.xsd` are different.

```
$ curl -s https://www.sii.cl/factura_electronica/schema_cesion.zip | md5sum
82d426fc3bd5f3a29e61a1d07ed4d6dd  -
$ curl -s https://www.sii.cl/factura_electronica/schema_cesion_201912.zip | md5sum
33639f61ef3aa0ec785557b1c8778cea  -
```

```suggestion
"[Formato XML del Archivo Electrónico de Cesión](https://www.sii.cl/factura_electronica/schema_cesion_201912.zip)"
```

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/2019-12-12-schema_cesion/schema_cesion/README.md
> +"[Formato XML del Archivo Electrónico de Cesión](http://www.sii.cl/factura_electronica/schema_cesion.zip)"
It may be better to simply reference the `Archivo Electrónico de Cesión` section of `src/code/rtc/2019-12-12-schema_cesion/README.md` to avoid duplicated text.

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/2019-12-12-schema_cesion/schema_cesion/README.md
> +- File `xmldsignature_v10.xsd` is identical to [xmldsignature_v10.xsd](../../../dte/2011-05-30-schema_dte/schema_dte/xmldsignature_v10.xsd) in the [DTE XML schema directory](../../../dte/2011-05-30-s
```suggestion
- File `xmldsignature_v10.xsd` is identical to [`xmldsignature_v10.xsd`](../../../dte/2011-05-30-schema_dte/schema_dte/xmldsignature_v10.xsd) in the [DTE XML schema directory](../../../dte/2011-05-30-schema_dte/schema_dte).
```

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/2019-12-12-schema_cesion/schema_cesion/README.md
> +This directory contains all the files of [2019-12-12-schema_cesion.zip](../README.md), plus this text file.
```suggestion
This directory contains all the files of [`2019-12-12-schema_cesion.zip`](../README.md), plus this text file.
```

2021-03-31 05:13 UTC, jtrh commented on src/code/rtc/2019-12-12-schema_cesion/schema_cesion/README.md
> +[schema_cesion_201912.zip](../README.md) (2019-12-12),
```suggestion
[`schema_cesion_201912.zip`](../README.md) (2019-12-12),
```

2021-03-31 06:43 UTC, yaselc commented on src/code/rtc/2019-12-12-schema_cesion/README.md
> +  "[Formato XML del Archivo Electrónico de Cesión](http://www.sii.cl/factura_electronica/schema_cesion.zip)"
> https://www.sii.cl/factura_electronica/schema_cesion.zip exists, but is a different file, possibly an older version. It contains the same files as `schema_cesion_201912.zip`, but `DTE_v10.xsd` and `SiiTypes_v10.xsd` are different.

Awesome! I completely missed it when I copied it from the original README posted by @glarrain, which was fine there but not for here, where we use the updated version.

2021-03-31 15:40 UTC, jtrh approved these changes

2021-03-31 15:43 UTC, merged